version: 2

jobs:
  deploy:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/juve534/sam-applications
    steps:
      - run:
          name: Install awscli
          command: |
            sudo apt-get update && sudo apt-get install -y awscli
      - checkout
      - run:
          name: build
          command: make build
      - run: aws cloudformation package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket sam-applications-trail
      - run: aws cloudformation deploy --template-file packaged.yaml --stack-name sam-applications-trail --capabilities CAPABILITY_IAM

workflows:
  version: 2
  default:
    jobs:
      - deploy:
          context: aws
          filters:
            branches:
              only: master
